### ISSUE TITLE
Incorrectly displayed WAITING tasks

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#10]
Tasks can be in WAITING state and we have no icon for them (empty state in the right panel). The word "WAITING" is also not seen on a task rectangle unless some other task is selected.

<img width="1397" alt="screen shot 2017-10-02 at 17 29 37" src="https://user-images.githubusercontent.com/1067142/31073736-53e2a1fa-a797-11e7-959c-50ce542a4904.png">

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
This should have been solved in v0.0.12.
Can you please verify?
