### ISSUE TITLE
Add a link to a parent workflow execution

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#11]
If the current workflow execution has a parent we need to display a link to it somewhere, probably at the top of the page.

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
Does the API `/executions/<id>/` exposes such parameter?

**Comment by rakhmerov** [comment]
Well, it's a little tricky now. You need to first get "task_execution_id", then using /tasks/<?> get a task and take its "workflow_execution_id". So it's possible but we have to make 2 additional requests which is not good, of course. I think we can do an optimization and insert "parent_workflow_execution_id" right into the execution object.

I guess we can postpone it. But once we do that it'll be easier to navigate.
