### ISSUE TITLE
Display "no child executions" if a task doesn't have action/workflow executions

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#13]
Now if a task execution doesn't have any child executions nothing is printed in the corresponding area, it's just empty. I'd suggest we display some phrase that would make it clear that the request to Mistral was made and there are no child executions associated with the task execution. Otherwise, it may seem that something is broken or Mistral still didn't respond.

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
What are the conditions for this to happen? Is it only a timing issue?
Also, is it correct to display "no child executions" if this is indeed a timing issue (which means "no child executions _yet_"?)

**Comment by rakhmerov** [comment]
It's not only a timing thing.

The conditions are the following:
* "Join" task which is not triggered yet (in WAITING state)
* A task with "pause-before" policy which is in IDLE state
* A task with "wait-before" policy which is in RUNNING_DELAYED state

**Comment by GuyShaanan** [comment]
Can you confirm the phrase (or suggest another one)?
![image](https://user-images.githubusercontent.com/7248108/32176001-2712717e-bd8f-11e7-9e86-271a78a76891.png)

Should the same text appear for subworkflow executions?

**Comment by rakhmerov** [comment]
Yes, sounds good to me.
