### ISSUE TITLE
"Execution ID" is not displayed when we select a task

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#14]
When we click on a particular task execution we don't see "Execution ID" anywhere. When investigating workflow failures it would be very convenient if we could also see it when clicking on a task execution.

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
Are your referring to "Workflow Execution ID" of that task?
Something like that: 
![image](https://user-images.githubusercontent.com/7248108/31584827-1ff3eb56-b1bf-11e7-83bb-00b639c9e2e6.png)

Taken from here:
![image](https://user-images.githubusercontent.com/7248108/31584836-444f533c-b1bf-11e7-84ad-655fe1cabc70.png)

?

**Comment by rakhmerov** [comment]
Yes, thanks.
