### ISSUE TITLE
Incorrectly displayed task definition sometimes

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#15]
When we click on "<>" in the right panel containing task execution details it sometimes displays task definition incorrectly.

<img width="823" alt="screen shot 2017-10-06 at 10 57 47" src="https://user-images.githubusercontent.com/1067142/31262476-6a18c7f6-aa85-11e7-8015-80fb437648ac.png">

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
What is being displayed incorrectly? Long lines? Empty lines?
Can you please attach a screenshot of what you think should look like?

**Comment by rakhmerov** [comment]
Sorry, this is not a bug. I was just expecting to see "action: ....", I thought I saw the definition of the entire workflow. But we can also have subworkflows.
