### ISSUE TITLE
Backwards navigation sometimes doesn't work well

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#17]
Sometimes when we click "back" button in the browser CloudFlow doesn't restore the previous view properly, it breaks. For example, if we clicked on the subworkflow and then try to go back to the parent workflow.

**Comment by GuyShaanan** [comment]
I've managed to reproduce the same error in the given scenario, but couldn't find other cases for this behavior.
A fixed will be available in next release.
