### ISSUE TITLE
Timeline view for executions

### ISSUE THREAD

**Issue by andrask** [nokia/CloudFlow#2]
It would be great to visualize the executions in the time dimension.
https://developers.google.com/chart/interactive/docs/gallery/timeline

**Comment by MosheElisha** [comment]
This is indeed a good idea.

In the past, when we tried thinking on how to implement this - we could not find a good solution on how to show task outcomes (on-success, on-error, ...) and joins in this view.
Maybe you have an idea?

This can also be an alternate view that focuses on the time dimension without the info of the exact call flow.

Another idea on how to add a time dimension to the current graph is described in issue  https://github.com/nokia/CloudFlow/issues/3 - will that also be good?

**Comment by andrask** [comment]
The timeline has a few features we can use:
- express duration with length
- express time points with the offset on the time axis
- express whatever with the labels and color of time-pieces

For starters, I would focus on visulalizing the natural timestamp-based ordering and the status of the tasks. The existing view seems to be more appropriate for exploring on-* relations. Efficient switching between the two views would be highly welcome.

Coloring in the current graph is also welcome, however, IMHO it may not be the best for expressing the time dimension.

**Comment by GuyShaanan** [comment]
"Timeline" feature will be a great addition, but it raises some other problems, like- we will soon add the ability to re-run a task and we need to ask ourselves how to show it in the timeline.

We currently focus on stability and some must-have features. Let me create a task out of this and we will address it in the near future.
Thanks for your input!

**Comment by prabvenu** [comment]
It would be a visual treat for the person who wants to understand about execution time frame for a given workflow.
