### ISSUE TITLE
Ability to find an object by ID

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#21]
It'd be really cool if we could quickly search a task or workflow execution by its id w/o having to navigate through many screens. I can't fully imagine though how it should look like but that would be super-awesome. For example, now I'm investigating an issue and I see that something is wrong with task whose ID is "1-2-3-4". It'd be great if I entered it in some search box and find it immediately and so that CloudFlow displays the correct part of the corresponding graph.

As far as whether it should be one field for both workflow and task executions, I don't know, we can think about that.

**Comment by GuyShaanan** [comment]
We'll do 3 separate calls:
* task execution
* workflow execution
* action execution

Then need to find the workflow execution id and navigate to the selected item (i.e /<workflow_execution_id>/<task_execution_id>)
