### ISSUE TITLE
Minor: Live demo link is broken.

### ISSUE THREAD

**Issue by galop** [nokia/CloudFlow#37]
The link [1] leads to an empty white screen but favicon and page title are correctly rendered.
However looking at page source, http://yaqluator.com:8000/ is working fine. Looks like the redirection is broken.

[1]. http://rawgit.com/nokia/CloudFlow/master/docs/index.html

**Comment by GuyShaanan** [comment]
Github is served via https and we are trying to load the demo site over http, and most recent browsers block this option. Hence the empty page.
Thanks for notifying.

As a temporary solution we changed the URL in the main page to directly point to our demo site.
