### ISSUE TITLE
Show more details on action execution

### ISSUE THREAD

**Issue by MosheElisha** [nokia/CloudFlow#5]
In addition to "Input" and "Output", please also display the action execution "ID", "State info", "Created at" and "Updated at".

**Comment by rakhmerov** [comment]
Can you please make this enhancement a high priority? This is really missing when it comes to investigating errors in workflows.

**Comment by GuyShaanan** [comment]
![image](https://user-images.githubusercontent.com/7248108/32721080-04e6cbec-c86e-11e7-9495-9313cc12a183.png)
Is this OK?

**Comment by rakhmerov** [comment]
Yes, looks very nice.
