### ISSUE TITLE
Pin "Definition" and "Graph" buttons at the top

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#6]
I think it would be useful if "Definition" and "Graph" buttons were always pinned at the top of the page. So we don't need to scroll them with the content.

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
There is an update to the GUI (to be introduced in next build) that removes these buttons and changes the layout a bit.
I'll close the issue once the build is out.

**Comment by rakhmerov** [comment]
Ok, sure.
