### ISSUE TITLE
"Full screen" modal window for json content is not really full screen

### ISSUE THREAD

**Issue by rakhmerov** [nokia/CloudFlow#9]
If we click "Open in fullscreen" button for any JSON content in the right hand side panel then we get a modal window. It's not nearly full full screen. Can we make it bigger and/or resizable?

<img width="1421" alt="screen shot 2017-10-02 at 15 08 16" src="https://user-images.githubusercontent.com/1067142/31068829-e777af28-a783-11e7-8ad0-6828c7472e3c.png">

CloudFlow version: v0.0.10

**Comment by GuyShaanan** [comment]
This has been changed in v0.0.12.
Can you confirm please?
